name: site-tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - cypress
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: install dependencies
        run: npm install

      - name: build site
        run: npm run build

      - name: test site with cypress
        uses: cypress-io/github-action@v5
        with:
          start: npx serve -s dist
          config: baseUrl=http://localhost:3000/#/
          wait-on: "http://localhost:3000/#/"
