name: Integration tests
on:
  push:
    branches:
      - cypress

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install

      # - name: Build
      #   run: npm run serve

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npx serve -s dist
          config: baseUrl=http://localhost:5000
          wait-on: "http://localhost:5000"

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
