name: Integration tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - cypress
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: build site
        run: npm run build

      - name: deploy site
        run: npx serve -s dist

      - name: test site with cypress
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=http://localhost:5000/#/
          wait-on: "http://localhost:5000/#/"
